version: '3.9'

networks:
  joyin-rh-net:
    driver: bridge

services:
  joyin-php:
    build: 
      context: .
      dockerfile: ./docker/php/DockerFile
    container_name: joyin-rh-container
    image: joyin-rh-app
    tty: true
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - mysql-joyin
    networks:
      - joyin-rh-net

  joyin-nginx:
    image: nginx:latest
    container_name: joyin-nginx-container
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    links:
      - joyin-php
    depends_on:
      - joyin-php
    networks:
      - joyin-rh-net
  
  mysql-joyin:
    image: mysql:latest
    container_name: mysql-joyin-container
    volumes:
     - ./docker/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test_dev
      MYSQL_DATABASE: joyin_test
      MYSQL_USER: joyin
      MYSQL_PASSWORD: test_dev
    networks:
      - joyin-rh-net